### PR TITLE
Modernize the build system

### LINKED ISSUE #13: Handle all Unix errors somehow
```
- File "lib/fs_common.ml", line 49, characters 2-489:
- Warning 8: this pattern-matching is not exhaustive.
- Here is an example of a value that is not matched:
- (E2BIG|EACCES|EAGAIN|EBADF|EBUSY|ECHILD|EDEADLK|EDOM|EFAULT|EFBIG|EINTR|
- EINVAL|EIO|EMFILE|EMLINK|ENAMETOOLONG|ENFILE|ENODEV|ENOEXEC|ENOLCK|ENOMEM|
- ENOSYS|ENOTTY|ENXIO|EPERM|EPIPE|ERANGE|EROFS|ESPIPE|ESRCH|EXDEV|EWOULDBLOCK|
- EINPROGRESS|EALREADY|ENOTSOCK|EDESTADDRREQ|EMSGSIZE|EPROTOTYPE|ENOPROTOOPT|
- EPROTONOSUPPORT|ESOCKTNOSUPPORT|EOPNOTSUPP|EPFNOSUPPORT|EAFNOSUPPORT|
- EADDRINUSE|EADDRNOTAVAIL|ENETDOWN|ENETUNREACH|ENETRESET|ECONNABORTED|
- ECONNRESET|ENOBUFS|EISCONN|ENOTCONN|ESHUTDOWN|ETOOMANYREFS|ETIMEDOUT|
- ECONNREFUSED|EHOSTDOWN|EHOSTUNREACH|ELOOP|EOVERFLOW)
```

### PR DESCRIPTION
**Pull request by samoht**
- add a .merlin file
- use topkg
- add missing mli files
- add docs

Also fixes #13 and #14 by turning on warning as error.

### CODE REVIEW

**Comment by yomimono** [comment]
Excellent overhaul, @samoht ! :)

**Comment by samoht** [comment]
Thanks! I squashed your changes with some other opam fixes (the `doc` field was incorrect).

Actually my goal with this would be to resolve #22 at some point, but not sure if I have the courage to dig into this today.

**Comment by yomimono** [comment]
I wanted to make a #courage joke but those are really only applicable to OSX problems.

**Comment by samoht** [comment]
All green, merging!

**Pull request merged**
